id: P779AAC6A
initial_creation_type: ocr
source_metadata:
  volumes:
    c97fd4b61a664453815ddbaa861f62b1:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1856
      volume_number: 14
